spring.application.name=desafio-estapar
server.port=3003

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/desafio_estapar?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

simulator.base-url=${SIMULATOR_BASE_URL:http://localhost:3000}
